# Generated by Django 5.2.17 on 2026-09-19 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import recruiting.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("resume", models.FileField(blank=True, upload_to=recruiting.models.resume_path)),
                ("resume_text", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("shortlisted", "Shortlisted"),
                            ("hold", "Hold"),
                            ("rejected", "Rejected"),
                            ("contacted", "Contacted"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="recruiting.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("status", models.CharField(db_index=True, default="queued", max_length=12)),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=80)),
                ("score", models.FloatField(null=True)),
                ("confidence", models.FloatField(null=True)),
                ("results", models.JSONField(default=list)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="recruiting.application",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="latest_evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recruiting.evaluation",
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField()),
                ("criteria", models.JSONField(default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruiting.job",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluation",
            constraint=models.UniqueConstraint(
                fields=("application", "job_version"), name="unique_evaluation_version"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["job", "stage", "id"], name="recruiting__job_id_ee7e37_idx"),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("job", "content_hash"), name="unique_resume_per_job"
            ),
        ),
    ]
