# Generated by Django 5.2.17 on 2026-09-19 05:26

from django.db import migrations, models

import recruiting.models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiting", "0002_remove_evaluation_unique_evaluation_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, max_length=500, upload_to=recruiting.models.resume_path
            ),
        ),
    ]
