# Generated by Django 5.2.17 on 2026-09-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_alter_resumescoringrun_owner_topcandidatesrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescoringrun',
            name='rubric_failure_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resumescoringrun',
            name='rubric_provider',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
