# Generated by Django 5.2.17 on 2026-09-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_resumescoringrun_rubric_failure_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumescoringrun',
            name='rubric_failure_reason',
        ),
        migrations.RemoveField(
            model_name='resumescoringrun',
            name='rubric_provider',
        ),
        migrations.AddField(
            model_name='resumescoringrun',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
